global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'support-api'
    static_configs:
      - targets: ['support-api:3000']

  - job_name: 'sentiment-ms'
    static_configs:
      - targets: ['sentiment-ms:8001']
